services:
  api:
    build:
      context: ./api
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./envs/api.env
      - ./envs/postgres.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - ./api:/app
    networks:
      - postgres_network

  postgres:
    image: postgres:15.2
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - envs/postgres.env
    ports:
      - "5432:5432"
    networks:
      - postgres_network

volumes:
  postgres_volume:

networks:
  postgres_network:
    driver: bridge
